apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: test
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30003 # 在这里定义 NodePort
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service-cluster
  namespace: test
spec:
  selector:
    app: mysql
  # clusterIP: None
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  # type: ClusterIP
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql 
        image: mysql:8.0.27
        securityContext:
           runAsUser: 1000
          #  privileged: true
        # command: ["sleep","100000"]
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: password
        volumeMounts: 
          - mountPath:  /var/lib/mysql
            name: db
          - mountPath: /etc/mysql/conf.d/
            name: mysql-config
      # - image: busybox
      #   securityContext:
      #       runAsUser: 1000
      #   name: busybox
      #   command: ["sleep"]
      #   args: ["100000"]
      #   volumeMounts: 
      #     - mountPath:  /var/lib/mysql/
      #       name: db
      #     - mountPath: /etc/mysql/config.d
      #       name: mysql-config
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-config 
          configMap:
            name:  "mysql-config"
