apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-local-volume
  namespace: test
  labels:
    type: local
spec:
  storageClassName: share-mysql
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  local:
    path: "/mnt/share/mysql"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - n1.local
