---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: test
  name: nginx-deployment-config-8080
  labels:
    app: nginx-deployment-config-8080
data:
  8080.conf: |
    server {
          listen        8080;
          #server_name  192.168.1.102;

          location /health {
              return 200 "health check";
          }
    
    }
    