---
apiVersion: v1
kind: Pod
metadata:
  name: appnginx
  namespace: test
  labels:
    app: appnginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
        - containerPort: 8080
      volumeMounts:
        - name: workdir
          mountPath: /mnt/share/nginx/html
  volumes:
    - name: workdir
      hostPath:
        path: /mnt/share/nginx/html