apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-pv-nas
  namespace: test
  labels:
    type: nas
spec:
  storageClassName: share-etcd
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: /export/test
    server: 192.168.160.132
