---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster
  namespace: test
  labels:
    app: redis-cluster
data:
  redis.conf: |
      bind 0.0.0.0
      port 6379
      cluster-announce-bus-port 16379
      cluster-enabled yes
      appendonly yes
      cluster-node-timeout 5000
      dir /data
      cluster-config-file /data/nodes.conf
      # requirepass pass123
      # masterauth pass123